[[redirects]]
force = true
from = '/api/*'
status = 200
to = '/.netlify/functions/:splat'

[[redirects]]
from = '/*'
status = 200
to = '/index.html'

[build]
command = 'npm run build'
publish = 'dist'
functions = "functions"

[dev]
autoLaunch = false
command = "npm run dev"